
url: "https://george-harper.xyz" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title: George Harper
email: geo.gh.213@gmail.com


description: >- # this means to ignore newlines until "baseurl:"
  My Profile

collections:
  projects:
    output: true
    permalink: /:collection/:name/


favicon: "/profile_fav.png"


navigation:
  - text: Home
    url: /
  - text: About
    url: /about/


markdown: kramdown
kmarkdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
